image: php:8.1-fpm

services:
  - mysql:latest

variables:
  DB_HOST: mysql
  DB_NAME: my_database
  DB_USER: root
  DB_PASSWORD: 

stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  script:
    - apt-get update && apt-get install -y unzip git
    - curl -sS https://getcomposer.org/installer | php
    - php composer.phar install

test_job:
  stage: test
  script:
    - php vendor/bin/phpunit --configuration phpunit.xml
  needs:
    - build_job

deploy_job:
  stage: deploy
  script:
    - echo "Deploying the application..."
    - # Comandos para deploy, como upload para o servidor ou execução de scripts de deploy
  only:
    - main
